version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: shareit-postgres
    restart: always
    environment:
      POSTGRES_DB: share_it
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: